In [1]:
%matplotlib inline


# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started
---------------

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.Tensor(5, 3)
print(x)


 1.7931e+36  4.5626e-41  1.7931e+36
 4.5626e-41  0.0000e+00  0.0000e+00
 7.0065e-45         nan  9.4482e-02
 3.0934e-41  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  9.8091e-45
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)


 0.6337  0.4056  0.5682
 0.5670  0.3852  0.2678
 0.6831  0.1997  0.9291
 0.2942  0.3611  0.8045
 0.7269  0.4637  0.9011
[torch.FloatTensor of size 5x3]



Get its size:



In [5]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

## Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [6]:
y = torch.rand(5, 3)
print(x + y)


 1.3278  0.5839  1.3150
 0.5917  1.1953  0.4741
 0.6877  0.5658  1.8912
 0.8965  1.1402  1.7240
 1.3404  0.6587  0.9736
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [7]:
print(torch.add(x, y))


 1.3278  0.5839  1.3150
 0.5917  1.1953  0.4741
 0.6877  0.5658  1.8912
 0.8965  1.1402  1.7240
 1.3404  0.6587  0.9736
[torch.FloatTensor of size 5x3]



Addition: providing an output tensor as argument



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.3278  0.5839  1.3150
 0.5917  1.1953  0.4741
 0.6877  0.5658  1.8912
 0.8965  1.1402  1.7240
 1.3404  0.6587  0.9736
[torch.FloatTensor of size 5x3]



Addition: in-place



In [9]:
# adds x to y
y.add_(x)
print(y)


 1.3278  0.5839  1.3150
 0.5917  1.1953  0.4741
 0.6877  0.5658  1.8912
 0.8965  1.1402  1.7240
 1.3404  0.6587  0.9736
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [10]:
x


 0.6337  0.4056  0.5682
 0.5670  0.3852  0.2678
 0.6831  0.1997  0.9291
 0.2942  0.3611  0.8045
 0.7269  0.4637  0.9011
[torch.FloatTensor of size 5x3]

In [11]:
x[torch.arange(5).numpy(), [0,1,2,1,0]]


 0.6337
 0.3852
 0.9291
 0.3611
 0.7269
[torch.FloatTensor of size 5]

Resizing: If you want to resize/reshape tensor, you can use ``torch.view`` method on a tensor. Note that this method returns a new tensor with the new specified dimension but the new tensor shares the same data with the origin tensor which calls the view. When one modifies the data of the view, they should expect that the data in the original tensor is also modified.



In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
y[0] = 99
print(y, x)


 99.0000
  0.8856
  1.1513
 -0.0272
 -0.8779
 -0.9948
 -0.4539
  0.6731
  0.8983
  0.3957
  0.2861
  0.3944
  1.5603
 -0.3554
  1.2646
  0.8006
[torch.FloatTensor of size 16]
 
 99.0000   0.8856   1.1513  -0.0272
 -0.8779  -0.9948  -0.4539   0.6731
  0.8983   0.3957   0.2861   0.3944
  1.5603  -0.3554   1.2646   0.8006
[torch.FloatTensor of size 4x4]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described [here](http://pytorch.org/docs/torch).

# NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

## Converting a Torch Tensor to a NumPy Array



In [14]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
type(b)

numpy.ndarray

See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` method.



In [19]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

/home/quang/anaconda3/envs/cs231n/lib/python3.6/site-packages/torch/tensor.py:293: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.add(other)


In [20]:
x.view(-1) + y


 198.0000
   1.7712
   2.3025
  -0.0545
  -1.7558
  -1.9895
  -0.9078
   1.3462
   1.7967
   0.7914
   0.5722
   0.7888
   3.1206
  -0.7109
   2.5291
   1.6012
[torch.cuda.FloatTensor of size 16 (GPU 0)]

In [21]:
torch.cuda.device_count()

1

In [22]:
torch.cuda.current_device()

0

In [23]:
torch.cuda.get_device_name(0)

'GeForce GTX 745'